title: Sergi Sanchez Orvay
author: S3RGI19
email: sergi.sanchez.orvay@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Sergi Sánchez Orvay's personal website. Robotics Engineer. AI, computer vision, robotics, perception and state estimation.
  ETH Zürich. Universitat Politècnica de Catalunya (UPC). IRI-CSIC.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Sergi Sánchez Orvay
  tagline: Robotics Engineer
  date_format: "%b %-d, %Y"
  style: black
  showPicker: false
  texture:
  showNav: true
  texture:
  showNav: true
  navigation:
    - title: About
      url: "/#about"
    - title: Skills
      url: "/#skills"
    - title: Projects
      url: "/#projects"
    - title: Contact
      url: "/#contact"



  # generate social links in footer
  social_links:
    github:  S3RGI19
    linkedIn: in/sergisanchezz
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed